version: '3.3'
services:
# React Service
  client:
    tty: true
    image: poleshe/react_client:firsttry
    ports:
     - "80:3000"
    command: "npm --prefix /usr/src/app run start"
    volumes:
     - "./client:/usr/src/app"
    networks:
     - app-network
# Laravel Service
  server:
    image: poleshe/laravel_server:firsttry
    ports:
     - "8000:80"
    volumes:
     - "./server:/var/www"
    networks:
     - app-network
#MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge